---
- name: Check whether Helm is already there
  stat:
    path: /usr/bin/helm
  register: helm_bin

- name: Retrieve helm binary archive
  unarchive:
    src: https://get.helm.sh/helm-v{{ helm.version }}-linux-{{ arch }}.tar.gz
    dest: /usr/bin
    remote_src: yes
    extra_opts: [--strip-components=1]
  when: helm_bin.stat.islnk is not defined
